package services

import (
	"bytes"
	"strings"
	"testing"
	"time"

	"qr-attendance-backend/internal/models"

	"github.com/xuri/excelize/v2"
)

// TestCSVFormulaInjectionSanitization ensures formula characters are escaped to prevent DDE execution
func TestCSVFormulaInjectionSanitization(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"Normal Name", "Rahul Sharma", "Rahul Sharma"},
		{"Normal Roll Number", "CS101", "CS101"},
		{"Formula starting with =", "=SUM(A1:A10)", "'=SUM(A1:A10)"},
		{"Formula starting with +", "+1234567890", "'+1234567890"},
		{"Formula starting with -", "-2+3*cmd|' /C calc'!A0", "'-2+3*cmd|' /C calc'!A0"},
		{"Formula starting with @", "@SUM(1+1)", "'@SUM(1+1)"},
		{"Formula starting with tab", "\tmalicious", "'\tmalicious"},
		{"Empty string", "", ""},
		{"Whitespace trimmed", "   =CMD()  ", "'=CMD()"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			actual := sanitizeCSVField(tt.input)
			if actual != tt.expected {
				t.Errorf("expected %q, got %q", tt.expected, actual)
			}
		})
	}
}

// TestGenerateAttendanceCSV verifies standards-compliant CSV generation with UTF-8 BOM
func TestGenerateAttendanceCSV(t *testing.T) {
	data := &AttendanceExportData{
		GeneratedAt: time.Now().UTC(),
		GeneratedBy: "Dr. Smith",
		Role:        models.RoleTeacher,
		Summary: AttendanceExportSummary{
			TotalStudents:        1,
			TotalSessions:        2,
			TotalPresent:         1,
			TotalAbsent:          1,
			OverallAttendancePct: 50.0,
		},
		DetailRows: []AttendanceExportRow{
			{
				StudentName:          "Alice Smith",
				RollNumber:           "CS101",
				Email:                "alice@college.edu",
				ClassName:            "BSc CS A",
				Department:           "Computer Science",
				Semester:             4,
				Section:              "A",
				SubjectName:          "Data Structures",
				SubjectCode:          "CS201",
				SessionDate:          "2026-08-10",
				SessionStartTime:     "09:00",
				SessionEndTime:       "10:00",
				AttendanceStatus:     "PRESENT",
				MarkedAt:             "09:05:12",
				AttendancePercentage: 50.0,
			},
		},
	}

	var buf bytes.Buffer
	err := GenerateAttendanceCSV(&buf, data)
	if err != nil {
		t.Fatalf("GenerateAttendanceCSV failed: %v", err)
	}

	output := buf.String()

	// Verify UTF-8 BOM at start
	if !strings.HasPrefix(output, "\xef\xbb\xbf") {
		t.Errorf("expected UTF-8 BOM prefix")
	}

	// Verify Header presence
	if !strings.Contains(output, "Student Name,Roll Number,Email,Class") {
		t.Errorf("header row missing in CSV output")
	}

	// Verify Data record presence
	if !strings.Contains(output, "Alice Smith,CS101,alice@college.edu,BSc CS A") {
		t.Errorf("student data missing in CSV output")
	}

	if !strings.Contains(output, "Data Structures,CS201,2026-08-10,09:00,10:00,PRESENT,09:05:12,50.0%") {
		t.Errorf("session data row missing in CSV output")
	}
}

// TestGenerateAttendanceExcel verifies valid XLSX workbook and multi-sheet generation
func TestGenerateAttendanceExcel(t *testing.T) {
	data := &AttendanceExportData{
		GeneratedAt: time.Now().UTC(),
		GeneratedBy: "Dr. Smith",
		Role:        models.RoleTeacher,
		Summary: AttendanceExportSummary{
			TotalStudents:              2,
			TotalSessions:              4,
			TotalPresent:               3,
			TotalAbsent:                1,
			OverallAttendancePct:       75.0,
			StudentsMeetingRequirement: 1,
			StudentsBelowRequirement:   1,
			StudentsCritical:           0,
		},
		DetailRows: []AttendanceExportRow{
			{
				StudentName:          "Bob Jones",
				RollNumber:           "CS102",
				Email:                "bob@college.edu",
				ClassName:            "BSc CS A",
				Department:           "Computer Science",
				Semester:             4,
				Section:              "A",
				SubjectName:          "Operating Systems",
				SubjectCode:          "CS202",
				SessionDate:          "2026-08-10",
				SessionStartTime:     "11:00",
				SessionEndTime:       "12:00",
				AttendanceStatus:     "PRESENT",
				MarkedAt:             "11:02:00",
				AttendancePercentage: 75.0,
			},
		},
	}

	bytesData, err := GenerateAttendanceExcel(data)
	if err != nil {
		t.Fatalf("GenerateAttendanceExcel failed: %v", err)
	}

	if len(bytesData) == 0 {
		t.Fatalf("expected non-empty XLSX bytes")
	}

	// Open generated bytes with excelize to verify valid structure
	f, err := excelize.OpenReader(bytes.NewReader(bytesData))
	if err != nil {
		t.Fatalf("failed to parse generated XLSX: %v", err)
	}
	defer f.Close()

	sheets := f.GetSheetList()
	if len(sheets) < 2 {
		t.Fatalf("expected at least 2 sheets, got %v", sheets)
	}

	if sheets[0] != "Attendance Report" || sheets[1] != "Summary" {
		t.Errorf("unexpected sheet names: %v", sheets)
	}

	// Check cell value in Attendance Report
	val, err := f.GetCellValue("Attendance Report", "A2")
	if err != nil || val != "Bob Jones" {
		t.Errorf("expected cell A2 to be 'Bob Jones', got %q (err: %v)", val, err)
	}
}

// TestGenerateAttendancePDF verifies landscape PDF generation
func TestGenerateAttendancePDF(t *testing.T) {
	data := &AttendanceExportData{
		GeneratedAt: time.Now().UTC(),
		GeneratedBy: "Prof. Alan Turing",
		Role:        models.RoleTeacher,
		Summary: AttendanceExportSummary{
			TotalStudents:              1,
			TotalSessions:              2,
			TotalPresent:               2,
			TotalAbsent:                0,
			OverallAttendancePct:       100.0,
			StudentsMeetingRequirement: 1,
			StudentsBelowRequirement:   0,
			StudentsCritical:           0,
		},
		DetailRows: []AttendanceExportRow{
			{
				StudentName:          "Charlie Brown",
				RollNumber:           "CS103",
				Email:                "charlie@college.edu",
				ClassName:            "BSc CS A",
				Department:           "Computer Science",
				Semester:             4,
				Section:              "A",
				SubjectName:          "Algorithms",
				SubjectCode:          "CS203",
				SessionDate:          "2026-08-10",
				SessionStartTime:     "14:00",
				SessionEndTime:       "15:00",
				AttendanceStatus:     "PRESENT",
				MarkedAt:             "14:01:30",
				AttendancePercentage: 100.0,
			},
		},
	}

	pdfBytes, err := GenerateAttendancePDF(data)
	if err != nil {
		t.Fatalf("GenerateAttendancePDF failed: %v", err)
	}

	if len(pdfBytes) == 0 {
		t.Fatalf("expected non-empty PDF byte slice")
	}

	// PDF files start with "%PDF-"
	if !strings.HasPrefix(string(pdfBytes[:8]), "%PDF-") {
		t.Errorf("output does not have valid PDF magic bytes header")
	}
}

// TestGenerateStudentDetailExportFormats tests individual student report generation across CSV, Excel, and PDF
func TestGenerateStudentDetailExportFormats(t *testing.T) {
	markedAt := time.Now().UTC()
	sampleDetail := &models.TeacherStudentAttendanceDetailResponse{
		Student: models.TeacherStudentBriefInfo{
			ID:         "stud-123",
			UserID:     "user-123",
			Name:       "John Doe",
			RollNumber: "CS105",
			Email:      "john@college.edu",
			ClassID:    "class-123",
			ClassName:  "BSc CS A",
			Department: "Computer Science",
			Semester:   4,
			Section:    "A",
		},
		Summary: models.TeacherStudentAttendanceDetailSummary{
			OverallPercentage: 80.0,
			TotalSessions:     10,
			TotalPresent:      8,
			TotalAbsent:       2,
			Status:            "REQUIREMENT_MET",
		},
		Subjects: []models.TeacherStudentAttendanceDetailSubject{
			{
				SubjectID:   "sub-1",
				SubjectName: "Computer Networks",
				SubjectCode: "CS204",
				Total:       10,
				Present:     8,
				Absent:      2,
				Percentage:  80.0,
				Status:      "REQUIREMENT_MET",
			},
		},
		History: models.TeacherStudentAttendanceDetailHistory{
			Records: []models.TeacherStudentAttendanceDetailHistoryRecord{
				{
					SessionID:   "sess-1",
					SubjectID:   "sub-1",
					SubjectName: "Computer Networks",
					SubjectCode: "CS204",
					StartedAt:   time.Now().UTC().Add(-2 * time.Hour),
					EndedAt:     time.Now().UTC().Add(-1 * time.Hour),
					Status:      "PRESENT",
					MarkedAt:    &markedAt,
				},
			},
		},
	}

	// 1. Test CSV
	var csvBuf bytes.Buffer
	if err := GenerateStudentDetailCSV(&csvBuf, sampleDetail); err != nil {
		t.Fatalf("GenerateStudentDetailCSV failed: %v", err)
	}
	if !strings.Contains(csvBuf.String(), "John Doe") || !strings.Contains(csvBuf.String(), "CS105") {
		t.Errorf("CSV missing student details")
	}

	// 2. Test Excel
	xlsxBytes, err := GenerateStudentDetailExcel(sampleDetail)
	if err != nil || len(xlsxBytes) == 0 {
		t.Fatalf("GenerateStudentDetailExcel failed: %v", err)
	}

	// 3. Test PDF
	pdfBytes, err := GenerateStudentDetailPDF(sampleDetail)
	if err != nil || len(pdfBytes) == 0 {
		t.Fatalf("GenerateStudentDetailPDF failed: %v", err)
	}
	if !strings.HasPrefix(string(pdfBytes[:8]), "%PDF-") {
		t.Errorf("student PDF does not have valid magic header")
	}
}
